/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppLearningRouteImport } from './routes/_app.learning'
import { Route as AppInterviewRouteImport } from './routes/_app.interview'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppRoadmapIndexRouteImport } from './routes/_app.roadmap.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppLearningIndexRouteImport } from './routes/_app.learning.index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as AppRoadmapTrackRouteImport } from './routes/_app.roadmap.$track'
import { Route as AppProjectsProjectRouteImport } from './routes/_app.projects.$project'
import { Route as AppLearningPythonRouteImport } from './routes/_app.learning.python'
import { Route as AppLearningCategoryRouteImport } from './routes/_app.learning.$category'
import { Route as AppLearningPythonIndexRouteImport } from './routes/_app.learning.python.index'
import { Route as AppCoursesCourseIndexRouteImport } from './routes/_app.courses.$course.index'
import { Route as AppLearningCategoryModuleRouteImport } from './routes/_app.learning.$category.$module'
import { Route as AppCoursesCourseLessonRouteImport } from './routes/_app.courses.$course.$lesson'
import { Route as AppLearningPythonModule1IndexRouteImport } from './routes/_app.learning.python.module-1.index'
import { Route as AppLearningPythonModule1CompleteRouteImport } from './routes/_app.learning.python.module-1.complete'
import { Route as AppLearningPythonModule1LessonRouteImport } from './routes/_app.learning.python.module-1.$lesson'
import { Route as AppLearningCategoryModuleLessonRouteImport } from './routes/_app.learning.$category.$module.$lesson'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapIndexRoute = AppRoadmapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoadmapRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppLearningIndexRoute = AppLearningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLearningRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppRoadmapTrackRoute = AppRoadmapTrackRouteImport.update({
  id: '/$track',
  path: '/$track',
  getParentRoute: () => AppRoadmapRoute,
} as any)
const AppProjectsProjectRoute = AppProjectsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppLearningPythonRoute = AppLearningPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => AppLearningRoute,
} as any)
const AppLearningCategoryRoute = AppLearningCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AppLearningRoute,
} as any)
const AppLearningPythonIndexRoute = AppLearningPythonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLearningPythonRoute,
} as any)
const AppCoursesCourseIndexRoute = AppCoursesCourseIndexRouteImport.update({
  id: '/$course/',
  path: '/$course/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppLearningCategoryModuleRoute =
  AppLearningCategoryModuleRouteImport.update({
    id: '/$module',
    path: '/$module',
    getParentRoute: () => AppLearningCategoryRoute,
  } as any)
const AppCoursesCourseLessonRoute = AppCoursesCourseLessonRouteImport.update({
  id: '/$course/$lesson',
  path: '/$course/$lesson',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppLearningPythonModule1IndexRoute =
  AppLearningPythonModule1IndexRouteImport.update({
    id: '/module-1/',
    path: '/module-1/',
    getParentRoute: () => AppLearningPythonRoute,
  } as any)
const AppLearningPythonModule1CompleteRoute =
  AppLearningPythonModule1CompleteRouteImport.update({
    id: '/module-1/complete',
    path: '/module-1/complete',
    getParentRoute: () => AppLearningPythonRoute,
  } as any)
const AppLearningPythonModule1LessonRoute =
  AppLearningPythonModule1LessonRouteImport.update({
    id: '/module-1/$lesson',
    path: '/module-1/$lesson',
    getParentRoute: () => AppLearningPythonRoute,
  } as any)
const AppLearningCategoryModuleLessonRoute =
  AppLearningCategoryModuleLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => AppLearningCategoryModuleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/interview': typeof AppInterviewRoute
  '/learning': typeof AppLearningRouteWithChildren
  '/notes': typeof AppNotesRoute
  '/progress': typeof AppProgressRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/resources': typeof AppResourcesRoute
  '/roadmap': typeof AppRoadmapRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/learning/$category': typeof AppLearningCategoryRouteWithChildren
  '/learning/python': typeof AppLearningPythonRouteWithChildren
  '/projects/$project': typeof AppProjectsProjectRoute
  '/roadmap/$track': typeof AppRoadmapTrackRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/learning/': typeof AppLearningIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/roadmap/': typeof AppRoadmapIndexRoute
  '/courses/$course/$lesson': typeof AppCoursesCourseLessonRoute
  '/learning/$category/$module': typeof AppLearningCategoryModuleRouteWithChildren
  '/courses/$course/': typeof AppCoursesCourseIndexRoute
  '/learning/python/': typeof AppLearningPythonIndexRoute
  '/learning/$category/$module/$lesson': typeof AppLearningCategoryModuleLessonRoute
  '/learning/python/module-1/$lesson': typeof AppLearningPythonModule1LessonRoute
  '/learning/python/module-1/complete': typeof AppLearningPythonModule1CompleteRoute
  '/learning/python/module-1/': typeof AppLearningPythonModule1IndexRoute
}
export interface FileRoutesByTo {
  '/interview': typeof AppInterviewRoute
  '/notes': typeof AppNotesRoute
  '/progress': typeof AppProgressRoute
  '/resources': typeof AppResourcesRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/learning/$category': typeof AppLearningCategoryRouteWithChildren
  '/projects/$project': typeof AppProjectsProjectRoute
  '/roadmap/$track': typeof AppRoadmapTrackRoute
  '/courses': typeof AppCoursesIndexRoute
  '/learning': typeof AppLearningIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/roadmap': typeof AppRoadmapIndexRoute
  '/courses/$course/$lesson': typeof AppCoursesCourseLessonRoute
  '/learning/$category/$module': typeof AppLearningCategoryModuleRouteWithChildren
  '/courses/$course': typeof AppCoursesCourseIndexRoute
  '/learning/python': typeof AppLearningPythonIndexRoute
  '/learning/$category/$module/$lesson': typeof AppLearningCategoryModuleLessonRoute
  '/learning/python/module-1/$lesson': typeof AppLearningPythonModule1LessonRoute
  '/learning/python/module-1/complete': typeof AppLearningPythonModule1CompleteRoute
  '/learning/python/module-1': typeof AppLearningPythonModule1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/interview': typeof AppInterviewRoute
  '/_app/learning': typeof AppLearningRouteWithChildren
  '/_app/notes': typeof AppNotesRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/resources': typeof AppResourcesRoute
  '/_app/roadmap': typeof AppRoadmapRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/learning/$category': typeof AppLearningCategoryRouteWithChildren
  '/_app/learning/python': typeof AppLearningPythonRouteWithChildren
  '/_app/projects/$project': typeof AppProjectsProjectRoute
  '/_app/roadmap/$track': typeof AppRoadmapTrackRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/learning/': typeof AppLearningIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/roadmap/': typeof AppRoadmapIndexRoute
  '/_app/courses/$course/$lesson': typeof AppCoursesCourseLessonRoute
  '/_app/learning/$category/$module': typeof AppLearningCategoryModuleRouteWithChildren
  '/_app/courses/$course/': typeof AppCoursesCourseIndexRoute
  '/_app/learning/python/': typeof AppLearningPythonIndexRoute
  '/_app/learning/$category/$module/$lesson': typeof AppLearningCategoryModuleLessonRoute
  '/_app/learning/python/module-1/$lesson': typeof AppLearningPythonModule1LessonRoute
  '/_app/learning/python/module-1/complete': typeof AppLearningPythonModule1CompleteRoute
  '/_app/learning/python/module-1/': typeof AppLearningPythonModule1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/interview'
    | '/learning'
    | '/notes'
    | '/progress'
    | '/projects'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/learning/$category'
    | '/learning/python'
    | '/projects/$project'
    | '/roadmap/$track'
    | '/courses/'
    | '/learning/'
    | '/projects/'
    | '/roadmap/'
    | '/courses/$course/$lesson'
    | '/learning/$category/$module'
    | '/courses/$course/'
    | '/learning/python/'
    | '/learning/$category/$module/$lesson'
    | '/learning/python/module-1/$lesson'
    | '/learning/python/module-1/complete'
    | '/learning/python/module-1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/interview'
    | '/notes'
    | '/progress'
    | '/resources'
    | '/settings'
    | '/'
    | '/learning/$category'
    | '/projects/$project'
    | '/roadmap/$track'
    | '/courses'
    | '/learning'
    | '/projects'
    | '/roadmap'
    | '/courses/$course/$lesson'
    | '/learning/$category/$module'
    | '/courses/$course'
    | '/learning/python'
    | '/learning/$category/$module/$lesson'
    | '/learning/python/module-1/$lesson'
    | '/learning/python/module-1/complete'
    | '/learning/python/module-1'
  id:
    | '__root__'
    | '/_app'
    | '/_app/courses'
    | '/_app/interview'
    | '/_app/learning'
    | '/_app/notes'
    | '/_app/progress'
    | '/_app/projects'
    | '/_app/resources'
    | '/_app/roadmap'
    | '/_app/settings'
    | '/_app/'
    | '/_app/learning/$category'
    | '/_app/learning/python'
    | '/_app/projects/$project'
    | '/_app/roadmap/$track'
    | '/_app/courses/'
    | '/_app/learning/'
    | '/_app/projects/'
    | '/_app/roadmap/'
    | '/_app/courses/$course/$lesson'
    | '/_app/learning/$category/$module'
    | '/_app/courses/$course/'
    | '/_app/learning/python/'
    | '/_app/learning/$category/$module/$lesson'
    | '/_app/learning/python/module-1/$lesson'
    | '/_app/learning/python/module-1/complete'
    | '/_app/learning/python/module-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning': {
      id: '/_app/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview': {
      id: '/_app/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap/': {
      id: '/_app/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof AppRoadmapIndexRouteImport
      parentRoute: typeof AppRoadmapRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/learning/': {
      id: '/_app/learning/'
      path: '/'
      fullPath: '/learning/'
      preLoaderRoute: typeof AppLearningIndexRouteImport
      parentRoute: typeof AppLearningRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/roadmap/$track': {
      id: '/_app/roadmap/$track'
      path: '/$track'
      fullPath: '/roadmap/$track'
      preLoaderRoute: typeof AppRoadmapTrackRouteImport
      parentRoute: typeof AppRoadmapRoute
    }
    '/_app/projects/$project': {
      id: '/_app/projects/$project'
      path: '/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof AppProjectsProjectRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/learning/python': {
      id: '/_app/learning/python'
      path: '/python'
      fullPath: '/learning/python'
      preLoaderRoute: typeof AppLearningPythonRouteImport
      parentRoute: typeof AppLearningRoute
    }
    '/_app/learning/$category': {
      id: '/_app/learning/$category'
      path: '/$category'
      fullPath: '/learning/$category'
      preLoaderRoute: typeof AppLearningCategoryRouteImport
      parentRoute: typeof AppLearningRoute
    }
    '/_app/learning/python/': {
      id: '/_app/learning/python/'
      path: '/'
      fullPath: '/learning/python/'
      preLoaderRoute: typeof AppLearningPythonIndexRouteImport
      parentRoute: typeof AppLearningPythonRoute
    }
    '/_app/courses/$course/': {
      id: '/_app/courses/$course/'
      path: '/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof AppCoursesCourseIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/learning/$category/$module': {
      id: '/_app/learning/$category/$module'
      path: '/$module'
      fullPath: '/learning/$category/$module'
      preLoaderRoute: typeof AppLearningCategoryModuleRouteImport
      parentRoute: typeof AppLearningCategoryRoute
    }
    '/_app/courses/$course/$lesson': {
      id: '/_app/courses/$course/$lesson'
      path: '/$course/$lesson'
      fullPath: '/courses/$course/$lesson'
      preLoaderRoute: typeof AppCoursesCourseLessonRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/learning/python/module-1/': {
      id: '/_app/learning/python/module-1/'
      path: '/module-1'
      fullPath: '/learning/python/module-1/'
      preLoaderRoute: typeof AppLearningPythonModule1IndexRouteImport
      parentRoute: typeof AppLearningPythonRoute
    }
    '/_app/learning/python/module-1/complete': {
      id: '/_app/learning/python/module-1/complete'
      path: '/module-1/complete'
      fullPath: '/learning/python/module-1/complete'
      preLoaderRoute: typeof AppLearningPythonModule1CompleteRouteImport
      parentRoute: typeof AppLearningPythonRoute
    }
    '/_app/learning/python/module-1/$lesson': {
      id: '/_app/learning/python/module-1/$lesson'
      path: '/module-1/$lesson'
      fullPath: '/learning/python/module-1/$lesson'
      preLoaderRoute: typeof AppLearningPythonModule1LessonRouteImport
      parentRoute: typeof AppLearningPythonRoute
    }
    '/_app/learning/$category/$module/$lesson': {
      id: '/_app/learning/$category/$module/$lesson'
      path: '/$lesson'
      fullPath: '/learning/$category/$module/$lesson'
      preLoaderRoute: typeof AppLearningCategoryModuleLessonRouteImport
      parentRoute: typeof AppLearningCategoryModuleRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesCourseLessonRoute: typeof AppCoursesCourseLessonRoute
  AppCoursesCourseIndexRoute: typeof AppCoursesCourseIndexRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesCourseLessonRoute: AppCoursesCourseLessonRoute,
  AppCoursesCourseIndexRoute: AppCoursesCourseIndexRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppLearningCategoryModuleRouteChildren {
  AppLearningCategoryModuleLessonRoute: typeof AppLearningCategoryModuleLessonRoute
}

const AppLearningCategoryModuleRouteChildren: AppLearningCategoryModuleRouteChildren =
  {
    AppLearningCategoryModuleLessonRoute: AppLearningCategoryModuleLessonRoute,
  }

const AppLearningCategoryModuleRouteWithChildren =
  AppLearningCategoryModuleRoute._addFileChildren(
    AppLearningCategoryModuleRouteChildren,
  )

interface AppLearningCategoryRouteChildren {
  AppLearningCategoryModuleRoute: typeof AppLearningCategoryModuleRouteWithChildren
}

const AppLearningCategoryRouteChildren: AppLearningCategoryRouteChildren = {
  AppLearningCategoryModuleRoute: AppLearningCategoryModuleRouteWithChildren,
}

const AppLearningCategoryRouteWithChildren =
  AppLearningCategoryRoute._addFileChildren(AppLearningCategoryRouteChildren)

interface AppLearningPythonRouteChildren {
  AppLearningPythonIndexRoute: typeof AppLearningPythonIndexRoute
  AppLearningPythonModule1LessonRoute: typeof AppLearningPythonModule1LessonRoute
  AppLearningPythonModule1CompleteRoute: typeof AppLearningPythonModule1CompleteRoute
  AppLearningPythonModule1IndexRoute: typeof AppLearningPythonModule1IndexRoute
}

const AppLearningPythonRouteChildren: AppLearningPythonRouteChildren = {
  AppLearningPythonIndexRoute: AppLearningPythonIndexRoute,
  AppLearningPythonModule1LessonRoute: AppLearningPythonModule1LessonRoute,
  AppLearningPythonModule1CompleteRoute: AppLearningPythonModule1CompleteRoute,
  AppLearningPythonModule1IndexRoute: AppLearningPythonModule1IndexRoute,
}

const AppLearningPythonRouteWithChildren =
  AppLearningPythonRoute._addFileChildren(AppLearningPythonRouteChildren)

interface AppLearningRouteChildren {
  AppLearningCategoryRoute: typeof AppLearningCategoryRouteWithChildren
  AppLearningPythonRoute: typeof AppLearningPythonRouteWithChildren
  AppLearningIndexRoute: typeof AppLearningIndexRoute
}

const AppLearningRouteChildren: AppLearningRouteChildren = {
  AppLearningCategoryRoute: AppLearningCategoryRouteWithChildren,
  AppLearningPythonRoute: AppLearningPythonRouteWithChildren,
  AppLearningIndexRoute: AppLearningIndexRoute,
}

const AppLearningRouteWithChildren = AppLearningRoute._addFileChildren(
  AppLearningRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectRoute: typeof AppProjectsProjectRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectRoute: AppProjectsProjectRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRoadmapRouteChildren {
  AppRoadmapTrackRoute: typeof AppRoadmapTrackRoute
  AppRoadmapIndexRoute: typeof AppRoadmapIndexRoute
}

const AppRoadmapRouteChildren: AppRoadmapRouteChildren = {
  AppRoadmapTrackRoute: AppRoadmapTrackRoute,
  AppRoadmapIndexRoute: AppRoadmapIndexRoute,
}

const AppRoadmapRouteWithChildren = AppRoadmapRoute._addFileChildren(
  AppRoadmapRouteChildren,
)

interface AppRouteChildren {
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppInterviewRoute: typeof AppInterviewRoute
  AppLearningRoute: typeof AppLearningRouteWithChildren
  AppNotesRoute: typeof AppNotesRoute
  AppProgressRoute: typeof AppProgressRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppResourcesRoute: typeof AppResourcesRoute
  AppRoadmapRoute: typeof AppRoadmapRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppInterviewRoute: AppInterviewRoute,
  AppLearningRoute: AppLearningRouteWithChildren,
  AppNotesRoute: AppNotesRoute,
  AppProgressRoute: AppProgressRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppResourcesRoute: AppResourcesRoute,
  AppRoadmapRoute: AppRoadmapRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
